version = 1
include = ["src/", "interfaces/"]
exclude = ["src/interfaces/external/"]

[detectors]
exclude = [
    "centralization-risk",
    "abi-encode-packed-hash-collision",
    "large-numeric-literal",
    "literal-instead-of-constant",
    "internal_function_used_once",
    "reentrancy-state-change",
    "push-zero-opcode",
    "address-state-variable-set-without-checks",
    "unchecked-return",
    "unspecific-solidity-pragma",
    "state_no_address_check",
]
