[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.35"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@morpho-blue/=lib/morpho-blue/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@yearn-erc4626-router/=lib/Yearn-ERC4626-Router/src/",
]
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./deployments"}]
no_match_path = "{test/fork/*,*Fork*}"
no_match_coverage = "script|test"

[rpc_endpoints]
flow_mainnet = "https://mainnet.evm.nodes.onflow.org"

[profile.ci]
no_match_path = "^$"
via_ir = true
optimizer_runs = 800
verbosity = 3
fuzz.runs = 10_000
deny = "notes"

[profile.local-ci]
no_match_path = "^$"
via_ir = true
optimizer_runs = 200
verbosity = 3
fuzz.runs = 10_000
deny = "notes"
[profile.local-ci.rpc_endpoints]
# anvil --fork-url https://mainnet.evm.nodes.onflow.org
flow_mainnet = "http://localhost:8545"

[fmt]
number_underscore = "thousands"
wrap_comments = true
docs_style = "line"
sort_imports = true

[lint]
severity = ["high", "medium", "low", "info", "gas", "codesize"]
exclude_lints = ["unaliased-plain-import", "asm-keccak256"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
